name: Docker Publish Pipeline
permissions:
  checks: write
  contents: write
  packages: write

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: >
      github.ref == 'refs/heads/main' || 
      (github.event_name == 'pull_request' && startsWith(github.head_ref, 'test/cicd-pipeline-test'))
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Short SHA for Docker Image
        run: echo "DOCKER_RELEASE_VERSION=${{ needs.build.outputs.application-version }}-${{ needs.build.outputs.commit-sha }}" >> $GITHUB_ENV

      - name: Set DOCKER IMAGE in lower case
        run: echo "DOCKER_IMAGE=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV   # Bash function to switch to lower case the environment variable.

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.13.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ env.DOCKER_IMAGE }}:latest, ghcr.io/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_RELEASE_VERSION }}
          build-args: | 
            GITHUB_USER=${{ github.actor }} 
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
